### ISSUE TITLE
CPU-only mode of pytorch

### ISSUE THREAD

**Issue by InquisitiveBloke** [emadalibrahim/Fusion-Cycle#2]
Hello,

I am trying to run Example_run.ipynb, but have encountered this:

`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
`
This is probably because my GPU does not meet pytorch requirements. So now I am trying to run pytorch in CPU-only mode.
From what I understand, some code should be added in Fusion_Cycle.py like this (probably preceded by `state_dict =` or something else):

`torch.load(map_location=torch.device('cpu'))`

I have tried multiple variations I found online, but nothing solved the error. It seems that the additional code must be adapted to Fusion-Cycle. My Python skills are limited, so I do not know how to do this or whether `torch.load` should contain other arguments.

**Comment by emadalibrahim** [comment]
Hi,

Thanks for you interest in our work.

I added the following code to the beginning of `Fusion-Cycle.py`

```
# Detect number of available CUDA devices
num_devices = torch.cuda.device_count()

if num_devices > 0:
    # If GPUs exist, pick device 0 by default
    os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    print(f"Using GPU device 0 (total available: {num_devices})")
else:
    # No GPUs → run on CPU
    os.environ["CUDA_VISIBLE_DEVICES"] = ""
    print("No GPU detected, running on CPU")
```

I think should fix it now...

**Comment by InquisitiveBloke** [comment]
Thank you for your quick answer.
I have updated my workspace with the latest code in the repository. The issue persists and is now preceded by a warning. I am including these together with the stack trace. I avoided the warning by downgrading to Python 3.10.18 and installing scikit-learn 1.0.2, but then got stuck with the featurizer not working on chemprop 1.6.1, so I returned to Python 3.13.7 and chemprop 2.2.1 which were used to obtain the code below.

```
0     False
1     False
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Name: solvent_density, Length: 100, dtype: bool
Model loaded successfully from '%USERPROFILE%\Fusion-Cycle-main\Density\qspr_density_model.pkl'.
Empty DataFrame
Columns: [solute_smiles_canonical, SMILES, solute_inchi, solute_smiles, solute_name, solvent_inchi, solvent_smiles, solvent_name, Temperature [K], Solubility, Solubility_units, source, Dataset, solute_MW, solvent_MW, solvent_density, solvent_density_warning, warning, logS, mole_fraction, dHfus_pred, dHfus_std, MP_pred, MP_std, ln_gamma_pred_i10, ln_gamma_std_i10, logS_calc_i10_PT, logS_calc_i0_PT, logS_calc_i0_FT, logS_calc_i10_FT, gamma, gamma_std, rho_R, Eelstat]
Index: []

[0 rows x 34 columns]
No valid data to predict for the missing rows.
[%USERPROFILE%\Fusion-Cycle-main\.conda\Lib\site-packages\sklearn\base.py:442](file:///%USERPROFILE%/Fusion-Cycle-main/.conda/Lib/site-packages/sklearn/base.py:442): InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.0.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
```

```
RuntimeError                              Traceback (most recent call last)
Cell In[3], [line 2](vscode-notebook-cell:?execution_count=3&line=2)
      1 model = Fusion_Cycle.model()
----> [2](vscode-notebook-cell:?execution_count=3&line=2) logS = model.calculate_solubility(df)

File %USERPROFILE%\Fusion-Cycle-main\Fusion_Cycle.py:231, in model.calculate_solubility(self, df)
    229 for i in range(self.Num_ensembles):
    230     checkpoint_path_list.append('trained_models/MP/model_'+str(i)+'.pt')
--> [231](file:///%USERPROFILE%/Fusion-Cycle-main/Fusion_Cycle.py:231) preds = self.predict_single(checkpoint_path_list,df)
    232 df['MP_pred'] = np.array(preds)[:,:,0].T.mean(axis=1)
    233 df['MP_std'] = np.array(preds)[:,:,0].T.std(axis=1)

File %USERPROFILE%\Fusion-Cycle-main\Fusion_Cycle.py:44, in model.predict_single(self, checkpoint_path_list, df_test)
     42     mpnn = models.MPNN.load_from_checkpoint(checkpoint_path)
     43 else:
---> [44](file:///%USERPROFILE%/Fusion-Cycle-main/Fusion_Cycle.py:44)     mpnn = models.MPNN.load_from_file(checkpoint_path)
     45 smiles_columns = 'solute_smiles_canonical' # name of the column containing SMILES strings
     46 smis = df_test[smiles_columns].values

File %USERPROFILE%\Fusion-Cycle-main\.conda\Lib\site-packages\chemprop\models\model.py:312, in MPNN.load_from_file(cls, model_path, map_location, strict, **submodules)
    310 @classmethod
    311 def load_from_file(cls, model_path, map_location=None, strict=True, **submodules) -> MPNN:
--> [312](file:///%USERPROFILE%/Fusion-Cycle-main/.conda/Lib/site-packages/chemprop/models/model.py:312)     submodules, state_dict, hparams = cls._load(model_path, map_location, **submodules)
    313     hparams.update(submodules)
...
    611     )
    612 if hasattr(device_module, "device_count"):
    613     device_count = device_module.device_count()

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by emadalibrahim** [comment]
Sorry about that.

We now set `device = torch.device("cpu")` and `map_location=device`

This should enable CPU runs

**Comment by InquisitiveBloke** [comment]
Thanks. This issue is now solved. The warning is also avoided.
